export { ChevronLeft } from './tabler/chevronLeft';
export { ChevronRight } from './tabler/chevronRight';
export { Building } from './tabler/Building';
export { BuildingBank } from './tabler/BuildingBank';
export { FileBarcode } from './tabler/FileBarcode';
export { Filter as tablerFilter } from './tabler/Filter';
export { SortDescending } from './tabler/SortDescending';
export { Photo } from './tabler/Photo';
export { Video } from './tabler/Video';
export { Star } from './tabler/Star';
export { ChevronDown } from './tabler/chevronDown';
export { DeviceFloppy } from './tabler/DeviceFloppy';
export { X } from './tabler/X';
export { ChevronUp } from './tabler/chevronUp';
export { Check as tablerCheck } from './tabler/Check';
export { Edit as Edittabler } from './tabler/Edit';
export { Trash as Trashtabler } from './tabler/Trash';
export { Refresh } from './tabler/Refresh';
export { Search as Searchtabler } from './tabler/Search';

export { AlertCircle } from './tabler/AlertCircle';
export { InfoCircle } from './tabler/InfoCircle';
export { Diamonds as Diamondstabler } from './tabler/Diamonds';
export { Diamond as Diamondtabler } from './tabler/Diamond';
export { ClipboardList } from './tabler/ClipboardList';
export { Settings } from './tabler/Settings';
export { TestPipe } from './tabler/TestPipe';
export { Flag } from './tabler/Flag';
export { Lock } from './tabler/Lock';
export { Logout } from './tabler/Logout';
export { Mail } from './tabler/Mail';
export { Server2 } from './tabler/Server2';
export { ShieldLock } from './tabler/ShieldLock';
export { TransferIn } from './tabler/TransferIn';
export { Users } from './tabler/Users';
export { Wallet } from './tabler/Wallet';
export { World } from './tabler/World';
export { Bell } from './tabler/Bell';
export { CurrencyEuro } from './tabler/CurrencyEuro';
export { AdjustmentsHorizontal } from './tabler/AdjustmentsHorizontal';
export { SortAscending } from './tabler/SortAscending';
export { ViewportNarrow } from './tabler/ViewportNarrow';
export { ViewportWide } from './tabler/ViewportWide';
export { Tag } from './tabler/Tag';

export { ShoppingCart } from './tabler/ShoppingCart';
export { ShoppingCartX } from './tabler/ShoppingCartX';

export { Heart as tablerHeart } from './tabler/Heart';
export { Copy as tablerCopy } from './tabler/Copy';
export { HandStop } from './tabler/HandStop';
export { ArrowsRightLeft } from './tabler/ArrowsRightLeft';
export { DotsVertical } from './tabler/DotsVertical';

export { MapPin } from './tabler/MapPin';
export { MapPins } from './tabler/MapPins';
export { ZoomQuestion } from './tabler/ZoomQuestion';
export { SwitchVertical } from './tabler/SwitchVertical';
export { HandOff } from './tabler/HandOff';
export { Eye } from './tabler/Eye';
export { EyeOff } from './tabler/EyeOff';
export { Clock } from './tabler/Clock';
export { ExternalLink } from './tabler/ExternalLink';
export { Select } from './tabler/Select';
export { InfoSquare } from './tabler/InfoSquare';
export { ArrowUpRight } from './tabler/ArrowUpRight';

export { Cash } from './tabler/Cash';
export { creditCard } from './tabler/creditCard';
export { CircleCheck } from './tabler/CircleCheck';
export { CalendarEvent } from './tabler/CalendarEvent';
export { ArrowLeft } from './tabler/ArrowLeft';

export { Calculator } from './tabler/Calculator';
export { Minus } from './tabler/Minus';
export { Plus } from './tabler/Plus';
export { ListCheck } from './tabler/ListCheck';
export { CheckupList } from './tabler/CheckupList';
export { TruckDelivery } from './tabler/TruckDelivery';
export { PackgeExport } from './tabler/PackgeExport';
export { PackgeOff } from './tabler/PackgeOff';
export { Ban } from './tabler/Ban';
export { TableExport } from './tabler/TableExport';
export { Reciept2 } from './tabler/Reciept2';
export { Flask } from './tabler/Flask';
export { Salad } from './tabler/Salad';

export { Bolt } from './tabler/Bolt';
export { Apple } from './tabler/Apple';
export { Buguette } from './tabler/Buguette';
